/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER PRY2206_P1 IDENTIFIED BY "PRY2206.practica_1"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER PRY2206_P1  QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO PRY2206_P1;
GRANT "RESOURCE" TO PRY2206_P1;
ALTER USER PRY2206_P1 DEFAULT ROLE "RESOURCE";

/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER PRY2206_P1 IDENTIFIED BY "PRY2206.practica_1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER PRY2206_P1  QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO PRY2206_P1;
GRANT "RESOURCE" TO PRY2206_P1;
ALTER USER PRY2206_P1 DEFAULT ROLE "RESOURCE";